create table "public"."mixtapes_authors" (
    "id" bigint generated by default as identity not null,
    "mixtape_id" bigint,
    "author_id" bigint,
    "position" smallint
);


alter table "public"."mixtapes_authors" enable row level security;

CREATE UNIQUE INDEX mixtapes_authors_pkey ON public.mixtapes_authors USING btree (id);

alter table "public"."mixtapes_authors" add constraint "mixtapes_authors_pkey" PRIMARY KEY using index "mixtapes_authors_pkey";

alter table "public"."mixtapes_authors" add constraint "mixtapes_authors_author_id_fkey" FOREIGN KEY (author_id) REFERENCES authors(id) not valid;

alter table "public"."mixtapes_authors" validate constraint "mixtapes_authors_author_id_fkey";

alter table "public"."mixtapes_authors" add constraint "mixtapes_authors_mixtape_id_fkey" FOREIGN KEY (mixtape_id) REFERENCES mixtapes(id) not valid;

alter table "public"."mixtapes_authors" validate constraint "mixtapes_authors_mixtape_id_fkey";


